#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Config-INI-Reader-Ordered
Version  : 0.020
Release  : 3
URL      : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Config-INI-Reader-Ordered-0.020.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Config-INI-Reader-Ordered-0.020.tar.gz
Summary  : '.ini-file parser that returns sections in order'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Config-INI-Reader-Ordered-license = %{version}-%{release}
Requires: perl-Config-INI-Reader-Ordered-perl = %{version}-%{release}
Requires: perl(Config::INI::Reader)
BuildRequires : buildreq-cpan
BuildRequires : perl(Config::INI::Reader)
BuildRequires : perl(Data::OptList)
BuildRequires : perl(Mixin::Linewise::Readers)
BuildRequires : perl(Params::Util)
BuildRequires : perl(PerlIO::utf8_strict)
BuildRequires : perl(Sub::Exporter)
BuildRequires : perl(Sub::Install)

%description
This archive contains the distribution Config-INI-Reader-Ordered,
version 0.020:

%package dev
Summary: dev components for the perl-Config-INI-Reader-Ordered package.
Group: Development
Provides: perl-Config-INI-Reader-Ordered-devel = %{version}-%{release}
Requires: perl-Config-INI-Reader-Ordered = %{version}-%{release}

%description dev
dev components for the perl-Config-INI-Reader-Ordered package.


%package license
Summary: license components for the perl-Config-INI-Reader-Ordered package.
Group: Default

%description license
license components for the perl-Config-INI-Reader-Ordered package.


%package perl
Summary: perl components for the perl-Config-INI-Reader-Ordered package.
Group: Default
Requires: perl-Config-INI-Reader-Ordered = %{version}-%{release}

%description perl
perl components for the perl-Config-INI-Reader-Ordered package.


%prep
%setup -q -n Config-INI-Reader-Ordered-0.020
cd %{_builddir}/Config-INI-Reader-Ordered-0.020

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Config-INI-Reader-Ordered
cp %{_builddir}/Config-INI-Reader-Ordered-0.020/LICENSE %{buildroot}/usr/share/package-licenses/perl-Config-INI-Reader-Ordered/bba56385737c5c107a36cf6a50072d12c574a7ce
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Config::INI::Reader::Ordered.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Config-INI-Reader-Ordered/bba56385737c5c107a36cf6a50072d12c574a7ce

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.1/Config/INI/Reader/Ordered.pm
